version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:80"  
    volumes:
      - ./src:/app/src  

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 

